### ISSUE TITLE
TRAIN output

### ISSUE THREAD

**Issue by sterbini** [giadarol/lhcmask#8]
Hi,
I am trying to test the flexibility of the mask to compute the TRAIN input files.

To do that one could use two different approaches.

(I) Use he general mask together with the 4 files
- mask_01_optics.madx
- mask_02_lumilevel_and_bb.madx
- mask_03_optics_and_err.madx
- mask_04_lasttwiss_and_sixtrack.madx

or (II) to write a new madx file.
Clearly, the first approach has the advantage to reduce the *.madx files to maintain but to make them more general.

*Example*: let us imagine we want to use the approach (I). TRAIN does need the BB lens as simple markers so one should at least put the charge of the BB lens to zero (or not install them, mask_02). In addition in mask_02 we need to reflect the lhcb2 sequence.
At the moment the errors (mask_03) are computed only for the sequence to track, if we would like to use also the errors in TRAIN we would need to compute the errors also for lhcb2 or, at least to, match the two sequences in terms of Q/chroma. 

What does the community prefer? Should we go for approach (I) or (II)?

**Comment by giadarol** [comment]
I consider duplicated code as the source of all evil.
I would go for option (I) and consider option (II) only if strictly needed.
